### ISSUE TITLE
Problem to run Main.py

### ISSUE THREAD

**Issue by SAEEDStarv** [NeverBehave/AlwaysOnline-#2]
When im enter this command : 

> python3 main.py

INFO:root:Trying to Login to Telegram... 正在尝试登录...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from login import client
  File "/root/AlwaysOnline-/login.py", line 14, in <module>
    client = TelegramClient('session_file', api_id, api_hash, update_workers=1, spawn_read_thread=False)
TypeError: __init__() got an unexpected keyword argument 'update_workers'

______________

There isn't problem in data.py

**Comment by NeverBehave** [comment]
updated

**Comment by SAEEDStarv** [comment]
Thanks.
